/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as NumerosRouteImport } from './routes/numeros'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as SaibaMaisRouteImport } from './routes/saiba-mais'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosRoute = NumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const SaibaMaisRoute = SaibaMaisRouteImport.update({
  id: '/saiba-mais',
  path: '/saiba-mais',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
  '/pautas': typeof PautasRoute
  '/saiba-mais': typeof SaibaMaisRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
  '/pautas': typeof PautasRoute
  '/saiba-mais': typeof SaibaMaisRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
  '/pautas': typeof PautasRoute
  '/saiba-mais': typeof SaibaMaisRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/midia' | '/numeros' | '/pautas' | '/saiba-mais' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/midia' | '/numeros' | '/pautas' | '/saiba-mais' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/midia'
    | '/numeros'
    | '/pautas'
    | '/saiba-mais'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MidiaRoute: typeof MidiaRoute
  NumerosRoute: typeof NumerosRoute
  PautasRoute: typeof PautasRoute
  SaibaMaisRoute: typeof SaibaMaisRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros': {
      id: '/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof NumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saiba-mais': {
      id: '/saiba-mais'
      path: '/saiba-mais'
      fullPath: '/saiba-mais'
      preLoaderRoute: typeof SaibaMaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MidiaRoute: MidiaRoute,
  NumerosRoute: NumerosRoute,
  PautasRoute: PautasRoute,
  SaibaMaisRoute: SaibaMaisRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
