/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PautasRouteImport } from './routes/pautas'
import { Route as MidiaRouteImport } from './routes/midia'
import { Route as NumerosRouteImport } from './routes/numeros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PautasRoute = PautasRouteImport.update({
  id: '/pautas',
  path: '/pautas',
  getParentRoute: () => rootRouteImport,
} as any)
const MidiaRoute = MidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerosRoute = NumerosRouteImport.update({
  id: '/numeros',
  path: '/numeros',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/pautas': typeof PautasRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/pautas': typeof PautasRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sobre': typeof SobreRoute
  '/pautas': typeof PautasRoute
  '/midia': typeof MidiaRoute
  '/numeros': typeof NumerosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sobre' | '/pautas' | '/midia' | '/numeros'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sobre' | '/pautas' | '/midia' | '/numeros'
  id: '__root__' | '/' | '/sobre' | '/pautas' | '/midia' | '/numeros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SobreRoute: typeof SobreRoute
  PautasRoute: typeof PautasRoute
  MidiaRoute: typeof MidiaRoute
  NumerosRoute: typeof NumerosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pautas': {
      id: '/pautas'
      path: '/pautas'
      fullPath: '/pautas'
      preLoaderRoute: typeof PautasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midia': {
      id: '/midia'
      path: '/midia'
      fullPath: '/midia'
      preLoaderRoute: typeof MidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros': {
      id: '/numeros'
      path: '/numeros'
      fullPath: '/numeros'
      preLoaderRoute: typeof NumerosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SobreRoute: SobreRoute,
  PautasRoute: PautasRoute,
  MidiaRoute: MidiaRoute,
  NumerosRoute: NumerosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
